// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/sealway-hq/sealway-verifier/packages/verifier/anchor"
	mock "github.com/stretchr/testify/mock"
)

// NewMockVerifier creates a new instance of MockVerifier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockVerifier(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockVerifier {
	mock := &MockVerifier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockVerifier is an autogenerated mock type for the Verifier type
type MockVerifier struct {
	mock.Mock
}

type MockVerifier_Expecter struct {
	mock *mock.Mock
}

func (_m *MockVerifier) EXPECT() *MockVerifier_Expecter {
	return &MockVerifier_Expecter{mock: &_m.Mock}
}

// Endpoint provides a mock function for the type MockVerifier
func (_mock *MockVerifier) Endpoint() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Endpoint")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockVerifier_Endpoint_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Endpoint'
type MockVerifier_Endpoint_Call struct {
	*mock.Call
}

// Endpoint is a helper method to define mock.On call
func (_e *MockVerifier_Expecter) Endpoint() *MockVerifier_Endpoint_Call {
	return &MockVerifier_Endpoint_Call{Call: _e.mock.On("Endpoint")}
}

func (_c *MockVerifier_Endpoint_Call) Run(run func()) *MockVerifier_Endpoint_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockVerifier_Endpoint_Call) Return(s string) *MockVerifier_Endpoint_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockVerifier_Endpoint_Call) RunAndReturn(run func() string) *MockVerifier_Endpoint_Call {
	_c.Call.Return(run)
	return _c
}

// Network provides a mock function for the type MockVerifier
func (_mock *MockVerifier) Network() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Network")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockVerifier_Network_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Network'
type MockVerifier_Network_Call struct {
	*mock.Call
}

// Network is a helper method to define mock.On call
func (_e *MockVerifier_Expecter) Network() *MockVerifier_Network_Call {
	return &MockVerifier_Network_Call{Call: _e.mock.On("Network")}
}

func (_c *MockVerifier_Network_Call) Run(run func()) *MockVerifier_Network_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockVerifier_Network_Call) Return(s string) *MockVerifier_Network_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockVerifier_Network_Call) RunAndReturn(run func() string) *MockVerifier_Network_Call {
	_c.Call.Return(run)
	return _c
}

// Verify provides a mock function for the type MockVerifier
func (_mock *MockVerifier) Verify(ctx context.Context, a anchor.Anchor, expectedRoot []byte) (*anchor.Result, error) {
	ret := _mock.Called(ctx, a, expectedRoot)

	if len(ret) == 0 {
		panic("no return value specified for Verify")
	}

	var r0 *anchor.Result
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, anchor.Anchor, []byte) (*anchor.Result, error)); ok {
		return returnFunc(ctx, a, expectedRoot)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, anchor.Anchor, []byte) *anchor.Result); ok {
		r0 = returnFunc(ctx, a, expectedRoot)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*anchor.Result)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, anchor.Anchor, []byte) error); ok {
		r1 = returnFunc(ctx, a, expectedRoot)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockVerifier_Verify_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Verify'
type MockVerifier_Verify_Call struct {
	*mock.Call
}

// Verify is a helper method to define mock.On call
//   - ctx context.Context
//   - a anchor.Anchor
//   - expectedRoot []byte
func (_e *MockVerifier_Expecter) Verify(ctx any, a any, expectedRoot any) *MockVerifier_Verify_Call {
	return &MockVerifier_Verify_Call{Call: _e.mock.On("Verify", ctx, a, expectedRoot)}
}

func (_c *MockVerifier_Verify_Call) Run(run func(ctx context.Context, a anchor.Anchor, expectedRoot []byte)) *MockVerifier_Verify_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 anchor.Anchor
		if args[1] != nil {
			arg1 = args[1].(anchor.Anchor)
		}
		var arg2 []byte
		if args[2] != nil {
			arg2 = args[2].([]byte)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockVerifier_Verify_Call) Return(result *anchor.Result, err error) *MockVerifier_Verify_Call {
	_c.Call.Return(result, err)
	return _c
}

func (_c *MockVerifier_Verify_Call) RunAndReturn(run func(ctx context.Context, a anchor.Anchor, expectedRoot []byte) (*anchor.Result, error)) *MockVerifier_Verify_Call {
	_c.Call.Return(run)
	return _c
}
